//! Renders the OpenBSD files for a resolved router. Pure: no I/O, so the
//! same output comes out on the router, in the build VM and in tests.

use std::fmt::Write as _;

use octopus_config::{Router, Secrets};
use serde::{Deserialize, Serialize};

mod analyzer;
mod dhcpd;
mod dns;
mod guard;
mod net;
pub mod nginx;
mod pf;
pub mod policy;
pub mod proxy;
mod services;
mod v6;
pub mod wifi;

pub use dns::zone_serial;

pub const HEADER: &str = "generated by octopus from router.toml; edit that, not this file";

/// What has to happen on the router when a file changes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Subsystem {
    Pf,
    Net,
    Dhcpd,
    Dns,
    Ntpd,
    Sshd,
    Syslogd,
    Rad,
    Dhcp6,
    Web,
    Resolv,
    Sysctl,
    Nginx,
    /// `relayd` in generations made before octopus-proxy replaced it
    #[serde(alias = "relayd")]
    Proxy,
    Collector,
    Analyzer,
    /// OpenWrt access points: their scripts are pushed over SSH
    Ap,
    /// A subsystem this version doesn't know (from a newer or older
    /// generation): its files are still written and removed, only the
    /// daemon actions are skipped, so rollback never fails on a name.
    #[serde(other)]
    Other,
}

impl Subsystem {
    pub fn name(self) -> &'static str {
        match self {
            Subsystem::Pf => "pf",
            Subsystem::Net => "net",
            Subsystem::Dhcpd => "dhcpd",
            Subsystem::Dns => "dns",
            Subsystem::Ntpd => "ntpd",
            Subsystem::Sshd => "sshd",
            Subsystem::Syslogd => "syslogd",
            Subsystem::Rad => "rad",
            Subsystem::Dhcp6 => "dhcp6leased",
            Subsystem::Web => "web",
            Subsystem::Resolv => "resolv",
            Subsystem::Sysctl => "sysctl",
            Subsystem::Nginx => "nginx",
            Subsystem::Proxy => "proxy",
            Subsystem::Collector => "collector",
            Subsystem::Analyzer => "analyzer",
            Subsystem::Ap => "ap",
            Subsystem::Other => "other",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutFile {
    /// Absolute target path on the router.
    pub path: String,
    pub content: String,
    pub mode: u32,
    pub owner: String,
    pub group: String,
    pub subsystem: Subsystem,
    /// Contains secret values: mode 0600, never shown in diffs.
    pub secret: bool,
}

/// A service's wanted state, applied with rcctl.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Service {
    pub name: String,
    pub enabled: bool,
    /// None leaves the flags at their default.
    pub flags: Option<String>,
    pub subsystem: Subsystem,
    /// Restart when its subsystem's files change (pflogd and the pf helper
    /// don't read them).
    #[serde(default = "yes")]
    pub restart: bool,
}

fn yes() -> bool {
    true
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Generation {
    pub files: Vec<OutFile>,
    pub services: Vec<Service>,
    /// Paths octopus owns: present in an older generation but not this one
    /// means delete. Globs are not used; hostname files are listed by name.
    pub notes: Vec<String>,
}

impl Generation {
    fn file(&mut self, path: impl Into<String>, content: String, sub: Subsystem) -> &mut OutFile {
        self.files.push(OutFile {
            path: path.into(),
            content,
            mode: 0o644,
            owner: "root".into(),
            group: "wheel".into(),
            subsystem: sub,
            secret: false,
        });
        self.files.last_mut().unwrap()
    }

    pub fn get(&self, path: &str) -> Option<&OutFile> {
        self.files.iter().find(|f| f.path == path)
    }
}

/// How secret references are filled in.
pub enum SecretSource<'a> {
    /// The real values (on the router, as root).
    Real(&'a Secrets),
    /// Placeholders (`check`, the web UI, CI): files still render and parse.
    Placeholder,
}

impl SecretSource<'_> {
    fn get(&self, reference: &str) -> Result<String, String> {
        let v = match self {
            SecretSource::Real(s) => s.resolve(reference)?.to_string(),
            SecretSource::Placeholder => {
                format!("PLACEHOLDER-{}", octopus_config::secrets::key_of(reference).unwrap_or("x"))
            }
        };
        // values end up inside single quotes in hostname.if(5) files
        if v.is_empty() || v.contains(['\'', '\n', '\r', '\\', '\0']) {
            return Err(format!("secret {reference}: empty or contains a quote, backslash or newline"));
        }
        Ok(v)
    }
}

pub fn render(r: &Router, secrets: &SecretSource) -> Result<Generation, String> {
    let mut g = Generation::default();
    pf::render(r, &mut g);
    net::render(r, secrets, &mut g)?;
    dhcpd::render(r, &mut g);
    dns::render(r, &mut g);
    services::render(r, &mut g);
    nginx::render(r, &mut g);
    v6::render(r, &mut g);
    proxy::render(r, &mut g);
    analyzer::render(r, &mut g);
    wifi::render(r, secrets, &mut g)?;
    guard::render(r, &mut g);
    g.files.sort_by(|a, b| a.path.cmp(&b.path));
    Ok(g)
}

/// `# header` lines for a config file.
fn header(comment: &str, extra: &[&str]) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "{comment} {HEADER}");
    for e in extra {
        let _ = writeln!(s, "{comment} {e}");
    }
    s.push('\n');
    s
}

#[cfg(test)]
mod tests;
