#!/bin/ksh
#
# Octopus web UI. Unprivileged; privileged actions go through doas(1)
# rules for /usr/local/sbin/octopus only (see /etc/doas.conf).

daemon="/usr/local/sbin/octopus-web"
daemon_user="_octoweb"
daemon_logger="daemon.info"

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO

rc_cmd $1
