#!/bin/ksh
#
# Octopus analyzer: locked BPF filters from FCAP rules, payload regex,
# ring-buffered pcaps in /var/octopus/pcap, lab blocks via the pf helper.

daemon="/usr/local/sbin/octopus-analyzer"
daemon_flags="-c /etc/octopus/analyzer.toml"
daemon_logger="daemon.info"

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO

rc_cmd $1
